export default [
  {
    id: 'sii-frontend-developer-react-js',
    nameCompany: 'Sii',
    mainTechnology: 'JavaScript',
    workplace: 'Frontend Developer React.js',
    salaryFrom: '10 000',
    salaryTo: '12 000',
    salaryCurrency: 'PLN',
    street: 'Grunwaldzka 20',
    city: 'Gdańsk',
    logoCompany:
      'https://bucket.justjoin.it/offers/company_logos/thumb/b4a0837f135fe43ab93209dbd8e4ce660cbd39b0.jpg?1576668518',
    technologies: ['javascript', 'react', 'redux'],
    technologyIcon: 'jsIcon',
    experience: 'mid',
    geoPosition: [54.375352, 18.616764],
    cityCategory: 'Trójmiasto',
    technologyCategory: 'JS'
  },
  {
    id: 'spartez-java-developer-junior',
    nameCompany: 'Spartez',
    mainTechnology: 'Java',
    workplace: 'Java Developer (Junior)',
    salaryFrom: '10 000',
    salaryTo: '12 000',
    salaryCurrency: 'PLN',
    street: 'aleja Wojska Polskiego 56',
    city: 'Gdańsk',
    logoCompany:
      'https://bucket.justjoin.it/offers/company_logos/thumb/0236ee4a819ba1115d26e23e3fa7485acbf2c9e7.png?1543918598',
    technologies: ['java', 'sql', 'docker'],
    technologyIcon: 'javaIcon',
    experience: 'junior',
    geoPosition: [54.388048, 18.582075],
    cityCategory: 'Trójmiasto',
    technologyCategory: 'Java'
  },
  {
    id: 'nigel-frank-international-senior-full-stack-developer-net',
    nameCompany: 'Nigel Frank International',
    mainTechnology: '.Net',
    workplace: 'Senior Full-Stack Developer .NET',
    salaryFrom: '13 000',
    salaryTo: '17 000',
    salaryCurrency: 'PLN',
    street: 'Centrum',
    city: 'Gdańsk',
    logoCompany:
      'https://bucket.justjoin.it/offers/company_logos/original/843d7eb87bfaa284d8c41a51b6617f046b1f7bb9.jpg?1569318064',
    technologies: ['.net', 'c#', 'wcf'],
    technologyIcon: 'dotNetIcon',
    experience: 'senior',
    geoPosition: [54.346955, 18.658874],
    cityCategory: 'Trójmiasto',
    technologyCategory: '.Net'
  },
  {
    id: 'itfs-angular-developer',
    nameCompany: 'ITFS',
    mainTechnology: 'JavaScript',
    workplace: 'Angular Developer',
    salaryFrom: '13 000',
    salaryTo: '13 500',
    salaryCurrency: 'PLN',
    street: 'Śródmieście',
    city: 'Gdańsk',
    logoCompany:
      'https://bucket.justjoin.it/offers/company_logos/original/ac615cba9a2507e51cca2bee63be83dea8f93680.jpg?1581953638',
    technologies: ['javascript', 'typescript', 'bootstrap'],
    technologyIcon: 'jsIcon',
    experience: 'mid',
    geoPosition: [54.344658, 18.65782],
    cityCategory: 'Trójmiasto',
    technologyCategory: 'JS'
  },
  {
    id: 'itds-reactjs-developer',
    nameCompany: 'ITDS',
    mainTechnology: 'JavaScript',
    workplace: 'ReactJs Developer',
    salaryFrom: '13 000',
    salaryTo: '18 000',
    salaryCurrency: 'PLN',
    street: 'Targ Drzewny 1',
    city: 'Gdańsk',
    logoCompany:
      'https://bucket.justjoin.it/offers/company_logos/original/e63f53525e45acd808a62116a7b5ff02f443026b.png?1581088427',
    technologies: ['javascript', 'react', 'redux'],
    technologyIcon: 'jsIcon',
    experience: 'mid',
    geoPosition: [54.351676, 18.64711],
    cityCategory: 'Trójmiasto',
    technologyCategory: 'JS'
  },
  {
    id: 'it-kontrakt-net-developer',
    nameCompany: 'IT Kontrakt',
    mainTechnology: '.Net',
    workplace: '.Net Developer',
    salaryFrom: '10 000',
    salaryTo: '16 000',
    salaryCurrency: 'PLN',
    street: 'Jana z Kolna 11',
    city: 'Gdańsk',
    logoCompany:
      'https://bucket.justjoin.it/offers/company_logos/original/05798c9158b3b8c2732d38947d34a7e21dfdc4e2.jpg?1574847848',
    technologies: ['.net', 'rest api', 'sql'],
    technologyIcon: 'dotNetIcon',
    experience: 'mid',
    geoPosition: [54.36047, 18.64716],
    cityCategory: 'Trójmiasto',
    technologyCategory: '.Net'
  },
  {
    id: 'steer-as-senior-c-sharp-developer',
    nameCompany: 'STEER AS',
    mainTechnology: 'C++',
    workplace: 'Senior C++ Developer',
    salaryFrom: '15 000',
    salaryTo: '19 000',
    salaryCurrency: 'PLN',
    street: 'Jana z Kolna 22/26',
    city: 'Gdańsk',
    logoCompany:
      'https://bucket.justjoin.it/offers/company_logos/original/00ee7331ecda6e47ba76491c5a3cdfbaf52b3946.png?1581519250',
    technologies: ['c++', 'linux', 'ros'],
    technologyIcon: 'cPlusPlusIcon',
    experience: 'senior',
    geoPosition: [54.36224, 18.646539],
    cityCategory: 'Trójmiasto',
    technologyCategory: 'C++'
  },
  {
    id: 'isolution-pl-sql-developer',
    nameCompany: 'Isolution',
    mainTechnology: 'Data',
    workplace: 'PL/SQL Developer',
    salaryFrom: '10 920',
    salaryTo: '15 960',
    salaryCurrency: 'PLN',
    street: 'Tyszkiewicza 21',
    city: 'Warszawa',
    logoCompany:
      'https://bucket.justjoin.it/offers/company_logos/original/8cbc91a494543cdc74e2c5837e5f2326a46e501b.png?1566547398',
    technologies: ['sql', 'git', 'oracle'],
    technologyIcon: 'dataIcon',
    experience: 'mid',
    geoPosition: [52.239764, 20.967216],
    cityCategory: 'Warszawa',
    technologyCategory: 'Data'
  },
  {
    id: 'set-on-target-net-developer',
    nameCompany: 'Set on Target',
    mainTechnology: '.Net',
    workplace: '.Net Developer',
    salaryFrom: '13 000',
    salaryTo: '18 000',
    salaryCurrency: 'PLN',
    street: 'Idzikowskiego 16',
    city: 'Warszawa',
    logoCompany:
      'https://bucket.justjoin.it/offers/company_logos/original/4ea733467b425ad3d8e982db962662b4ede6daa4.png?1581413364',
    technologies: ['.net', 'c#', 'wpf'],
    technologyIcon: 'dotNetIcon',
    experience: 'senior',
    geoPosition: [52.192301, 21.046892],
    cityCategory: 'Warszawa',
    technologyCategory: '.Net'
  },
  {
    id: 'mokimo-frontend-developer',
    nameCompany: 'Makimo',
    mainTechnology: 'JavaScript',
    workplace: 'Frontend Developer',
    salaryFrom: '6 500',
    salaryTo: '10 500',
    salaryCurrency: 'PLN',
    street: 'Łąkowa 7A',
    city: 'Łódź',
    logoCompany:
      'https://bucket.justjoin.it/offers/company_logos/original/9463733bb39a46ca480a6f6d19fcb2f0dfbcb5f5.jpg?1575286491',
    technologies: ['javascript', 'git', 'react'],
    technologyIcon: 'jsIcon',
    experience: 'mid',
    geoPosition: [51.761845, 19.438644],
    cityCategory: 'Łódź',
    technologyCategory: 'JS'
  },
  {
    id: 'optimo-developer-python-software-developer',
    nameCompany: 'Optimo Development',
    mainTechnology: 'Python',
    workplace: 'Python Software Developer',
    salaryFrom: '10 000',
    salaryTo: '15 000',
    salaryCurrency: 'PLN',
    street: 'Piotrkowska 280 A',
    city: 'Łódź',
    logoCompany:
      'https://bucket.justjoin.it/offers/company_logos/original/98545dfd794ddc4cef49eef6ea99498ecdaccdee.png?1577782424',
    technologies: ['python', 'celery', 'git'],
    technologyIcon: 'pythonIcon',
    experience: 'senior',
    geoPosition: [51.74581, 19.461549],
    cityCategory: 'Łódź',
    technologyCategory: 'Python'
  },
  {
    id: 'appsgardern-frontend-developer',
    nameCompany: 'appsgarden',
    mainTechnology: 'JavaScript',
    workplace: 'Frontend Developer',
    salaryFrom: '4 000',
    salaryTo: '6 000',
    salaryCurrency: 'PLN',
    street: 'Makuszyńskiego 4',
    city: 'Kraków',
    logoCompany:
      'https://bucket.justjoin.it/offers/company_logos/original/2834b269600924d94d6065044ad3a1e25ce19caf.png?1544094879',
    technologies: ['react', 'angular', 'git'],
    technologyIcon: 'jsIcon',
    experience: 'mid',
    geoPosition: [50.08736, 20.048559],
    cityCategory: 'Kraków',
    technologyCategory: 'JS'
  }
]
