export default [
  {
    id: 'sii-frontend-developer-react-js',
    companyName: 'Sii',
    mainTechnology: 'JavaScript',
    workplace: 'Frontend Developer React.js',
    salaryFrom: '10 000',
    salaryTo: '12 000',
    salaryCurrency: 'PLN',
    companySize: '200+',
    employmentType: 'b2b',
    publishedAt: '',
    companyUrl: 'https://sii.pl/',
    street: 'Grunwaldzka 20',
    city: 'Gdańsk',
    companyLogo:
      'https://bucket.justjoin.it/offers/company_logos/thumb/b4a0837f135fe43ab93209dbd8e4ce660cbd39b0.jpg?1576668518',
    technologies: ['javascript', 'react', 'redux'],
    technologyIcon: 'jsIcon',
    experienceLevel: 'mid',
    geoPosition: [54.375352, 18.616764],
    cityCategory: 'Trójmiasto',
    technologyCategory: 'JS',
    skills: [
      { name: 'JS', level: 3 },
      { name: 'ReactJS', level: 3 },
      { name: 'MongoDB', level: 3 },
      { name: 'ReactJS', level: 3 },
      { name: 'MongoDB', level: 3 },
      { name: 'ReactJS', level: 3 },
      { name: 'MongoDB', level: 3 },
      { name: 'ReactJS', level: 3 },
      { name: 'MongoDB', level: 3 },
      { name: 'NodeJS', level: 3 }
    ],
    body:
      '<div>For our client, an international IT company<strong><em>,</em></strong> we realize a recruitment process on the position (Senior) Backend (Node.js) Developer to the long-term project.</div><div><br></div><div><strong>Information about the project</strong></div><div>We are implementing a self-service and webshop for one of the biggest teleoperators in Finland. We have in total around 30 people working for the project. We are using modern, agile working practices that really appreciates the developers and people have many possibilities to affect the work and how it is done. <br><strong>It is possible to work remotely part-time.</strong></div><div><br></div><div><strong>An ideal candidate profile:</strong></div><ul><li>Very good knowledge of Node.js</li><li>Very good knowledge of JavaScript (there is using Typescript in top of Javascript)</li><li>Good knowledge of REST and/or GraphQL</li><li>Docker knowledge will be a big plus</li></ul><div><br></div><div><strong>Our offer:</strong></div><ul><li>B2B agreement</li><li>Transparent working conditions with both Ework and the Client</li><li>Current support during our cooperation</li><li>Private medical care</li><li>Life insurance</li><li>Multisport</li><li>Teambuilding events</li></ul>'
  },
  {
    id: 'spartez-java-developer-junior',
    companyName: 'Spartez',
    mainTechnology: 'Java',
    workplace: 'Java Developer (Junior)',
    salaryFrom: '10 000',
    salaryTo: '12 000',
    salaryCurrency: 'PLN',
    companySize: '100+',
    employmentType: 'Pernament',
    publishedAt: '',
    companyUrl: 'https://spartez.com/',
    street: 'Winogrady',
    city: 'Poznań',
    companyLogo:
      'https://bucket.justjoin.it/offers/company_logos/thumb/0236ee4a819ba1115d26e23e3fa7485acbf2c9e7.png?1543918598',
    technologies: ['java', 'sql', 'docker'],
    technologyIcon: 'javaIcon',
    experienceLevel: 'junior',
    geoPosition: [52.416834, 16.936764],
    cityCategory: 'Poznań',
    technologyCategory: 'Java',
    skills: [
      { name: 'JS', level: 3 },
      { name: 'ReactJS', level: 3 },
      { name: 'MongoDB', level: 3 },
      { name: 'NodeJS', level: 3 }
    ],
    body:
      '<div>For our client, an international IT company<strong><em>,</em></strong> we realize a recruitment process on the position (Senior) Backend (Node.js) Developer to the long-term project.</div><div><br></div><div><strong>Information about the project</strong></div><div>We are implementing a self-service and webshop for one of the biggest teleoperators in Finland. We have in total around 30 people working for the project. We are using modern, agile working practices that really appreciates the developers and people have many possibilities to affect the work and how it is done. <br><strong>It is possible to work remotely part-time.</strong></div><div><br></div><div><strong>An ideal candidate profile:</strong></div><ul><li>Very good knowledge of Node.js</li><li>Very good knowledge of JavaScript (there is using Typescript in top of Javascript)</li><li>Good knowledge of REST and/or GraphQL</li><li>Docker knowledge will be a big plus</li></ul><div><br></div><div><strong>Our offer:</strong></div><ul><li>B2B agreement</li><li>Transparent working conditions with both Ework and the Client</li><li>Current support during our cooperation</li><li>Private medical care</li><li>Life insurance</li><li>Multisport</li><li>Teambuilding events</li></ul>'
  },
  {
    id: 'nigel-frank-international-senior-full-stack-developer-net',
    companyName: 'Nigel Frank International',
    mainTechnology: '.Net',
    workplace: 'Senior Full-Stack Developer .NET',
    salaryFrom: '13 000',
    salaryTo: '17 000',
    salaryCurrency: 'PLN',
    companySize: '50+',
    employmentType: 'b2b',
    publishedAt: '',
    companyUrl: 'https://www.nigelfrank.com/pl/',
    street: 'Centrum',
    city: 'Gdańsk',
    companyLogo:
      'https://bucket.justjoin.it/offers/company_logos/original/843d7eb87bfaa284d8c41a51b6617f046b1f7bb9.jpg?1569318064',
    technologies: ['.net', 'c#', 'wcf'],
    technologyIcon: 'dotNetIcon',
    experienceLevel: 'senior',
    geoPosition: [54.346955, 18.658874],
    cityCategory: 'Trójmiasto',
    technologyCategory: '.Net',
    skills: [
      { name: 'JS', level: 3 },
      { name: 'ReactJS', level: 3 },
      { name: 'MongoDB', level: 3 },
      { name: 'NodeJS', level: 3 }
    ],
    body:
      '<div>For our client, an international IT company<strong><em>,</em></strong> we realize a recruitment process on the position (Senior) Backend (Node.js) Developer to the long-term project.</div><div><br></div><div><strong>Information about the project</strong></div><div>We are implementing a self-service and webshop for one of the biggest teleoperators in Finland. We have in total around 30 people working for the project. We are using modern, agile working practices that really appreciates the developers and people have many possibilities to affect the work and how it is done. <br><strong>It is possible to work remotely part-time.</strong></div><div><br></div><div><strong>An ideal candidate profile:</strong></div><ul><li>Very good knowledge of Node.js</li><li>Very good knowledge of JavaScript (there is using Typescript in top of Javascript)</li><li>Good knowledge of REST and/or GraphQL</li><li>Docker knowledge will be a big plus</li></ul><div><br></div><div><strong>Our offer:</strong></div><ul><li>B2B agreement</li><li>Transparent working conditions with both Ework and the Client</li><li>Current support during our cooperation</li><li>Private medical care</li><li>Life insurance</li><li>Multisport</li><li>Teambuilding events</li></ul>'
  },
  {
    id: 'itfs-angular-developer',
    companyName: 'ITFS',
    mainTechnology: 'JavaScript',
    workplace: 'Angular Developer',
    salaryFrom: '13 000',
    salaryTo: '14 000',
    salaryCurrency: 'PLN',
    companySize: '20-30',
    employmentType: 'Pernament',
    publishedAt: '',
    companyUrl: 'https://itfs.pl/',
    street: 'Kuźnicza 49',
    city: 'Wrocław',
    companyLogo:
      'https://bucket.justjoin.it/offers/company_logos/original/ac615cba9a2507e51cca2bee63be83dea8f93680.jpg?1581953638',
    technologies: ['javascript', 'typescript', 'bootstrap'],
    technologyIcon: 'jsIcon',
    experienceLevel: 'mid',
    geoPosition: [51.11243, 17.033533],
    cityCategory: 'Wrocław',
    technologyCategory: 'JS',
    skills: [
      { name: 'JS', level: 3 },
      { name: 'ReactJS', level: 3 },
      { name: 'MongoDB', level: 3 },
      { name: 'NodeJS', level: 3 }
    ],
    body:
      '<div>For our client, an international IT company<strong><em>,</em></strong> we realize a recruitment process on the position (Senior) Backend (Node.js) Developer to the long-term project.</div><div><br></div><div><strong>Information about the project</strong></div><div>We are implementing a self-service and webshop for one of the biggest teleoperators in Finland. We have in total around 30 people working for the project. We are using modern, agile working practices that really appreciates the developers and people have many possibilities to affect the work and how it is done. <br><strong>It is possible to work remotely part-time.</strong></div><div><br></div><div><strong>An ideal candidate profile:</strong></div><ul><li>Very good knowledge of Node.js</li><li>Very good knowledge of JavaScript (there is using Typescript in top of Javascript)</li><li>Good knowledge of REST and/or GraphQL</li><li>Docker knowledge will be a big plus</li></ul><div><br></div><div><strong>Our offer:</strong></div><ul><li>B2B agreement</li><li>Transparent working conditions with both Ework and the Client</li><li>Current support during our cooperation</li><li>Private medical care</li><li>Life insurance</li><li>Multisport</li><li>Teambuilding events</li></ul>'
  },
  {
    id: 'itds-reactjs-developer',
    companyName: 'ITDS',
    mainTechnology: 'JavaScript',
    workplace: 'ReactJs Developer',
    salaryFrom: '13 000',
    salaryTo: '18 000',
    salaryCurrency: 'PLN',
    companySize: '10-20',
    employmentType: 'Pernament',
    publishedAt: '',
    companyUrl: 'https://itds.pl/',
    street: 'Aleje Adama Mickiewicza 19-11',
    city: 'Bydgoszcz',
    companyLogo:
      'https://bucket.justjoin.it/offers/company_logos/original/e63f53525e45acd808a62116a7b5ff02f443026b.png?1581088427',
    technologies: ['javascript', 'react', 'redux'],
    technologyIcon: 'jsIcon',
    experienceLevel: 'mid',
    geoPosition: [53.131164, 18.012517],
    cityCategory: 'Bydgoszcz',
    technologyCategory: 'JS',
    skills: [
      { name: 'JS', level: 3 },
      { name: 'ReactJS', level: 3 },
      { name: 'MongoDB', level: 3 },
      { name: 'NodeJS', level: 3 }
    ],
    body:
      '<div>For our client, an international IT company<strong><em>,</em></strong> we realize a recruitment process on the position (Senior) Backend (Node.js) Developer to the long-term project.</div><div><br></div><div><strong>Information about the project</strong></div><div>We are implementing a self-service and webshop for one of the biggest teleoperators in Finland. We have in total around 30 people working for the project. We are using modern, agile working practices that really appreciates the developers and people have many possibilities to affect the work and how it is done. <br><strong>It is possible to work remotely part-time.</strong></div><div><br></div><div><strong>An ideal candidate profile:</strong></div><ul><li>Very good knowledge of Node.js</li><li>Very good knowledge of JavaScript (there is using Typescript in top of Javascript)</li><li>Good knowledge of REST and/or GraphQL</li><li>Docker knowledge will be a big plus</li></ul><div><br></div><div><strong>Our offer:</strong></div><ul><li>B2B agreement</li><li>Transparent working conditions with both Ework and the Client</li><li>Current support during our cooperation</li><li>Private medical care</li><li>Life insurance</li><li>Multisport</li><li>Teambuilding events</li></ul>'
  },
  {
    id: 'it-kontrakt-net-developer',
    companyName: 'IT Kontrakt',
    mainTechnology: '.Net',
    workplace: '.Net Developer',
    salaryFrom: '10 000',
    salaryTo: '16 000',
    salaryCurrency: 'PLN',
    companySize: '50-60',
    employmentType: 'b2b',
    publishedAt: '',
    companyUrl: 'https://www.itkontrakt.pl/',
    street: 'Jana z Kolna 11',
    city: 'Gdańsk',
    companyLogo:
      'https://bucket.justjoin.it/offers/company_logos/original/05798c9158b3b8c2732d38947d34a7e21dfdc4e2.jpg?1574847848',
    technologies: ['.net', 'rest api', 'sql'],
    technologyIcon: 'dotNetIcon',
    experienceLevel: 'mid',
    geoPosition: [54.36047, 18.64716],
    cityCategory: 'Trójmiasto',
    technologyCategory: '.Net',
    skills: [
      { name: 'JS', level: 3 },
      { name: 'ReactJS', level: 3 },
      { name: 'MongoDB', level: 3 },
      { name: 'NodeJS', level: 3 }
    ],
    body:
      '<div>For our client, an international IT company<strong><em>,</em></strong> we realize a recruitment process on the position (Senior) Backend (Node.js) Developer to the long-term project.</div><div><br></div><div><strong>Information about the project</strong></div><div>We are implementing a self-service and webshop for one of the biggest teleoperators in Finland. We have in total around 30 people working for the project. We are using modern, agile working practices that really appreciates the developers and people have many possibilities to affect the work and how it is done. <br><strong>It is possible to work remotely part-time.</strong></div><div><br></div><div><strong>An ideal candidate profile:</strong></div><ul><li>Very good knowledge of Node.js</li><li>Very good knowledge of JavaScript (there is using Typescript in top of Javascript)</li><li>Good knowledge of REST and/or GraphQL</li><li>Docker knowledge will be a big plus</li></ul><div><br></div><div><strong>Our offer:</strong></div><ul><li>B2B agreement</li><li>Transparent working conditions with both Ework and the Client</li><li>Current support during our cooperation</li><li>Private medical care</li><li>Life insurance</li><li>Multisport</li><li>Teambuilding events</li></ul>'
  },
  {
    id: 'steer-as-senior-c-sharp-developer',
    companyName: 'STEER AS',
    mainTechnology: 'C++',
    workplace: 'Senior C++ Developer',
    salaryFrom: '15 000',
    salaryTo: '19 000',
    salaryCurrency: 'PLN',
    companySize: '150+',
    employmentType: 'Pernament',
    publishedAt: '',
    companyUrl: 'https://www.steer.no/',
    street: 'Jana z Kolna 22/26',
    city: 'Gdańsk',
    companyLogo:
      'https://bucket.justjoin.it/offers/company_logos/original/00ee7331ecda6e47ba76491c5a3cdfbaf52b3946.png?1581519250',
    technologies: ['c++', 'linux', 'ros'],
    technologyIcon: 'cPlusPlusIcon',
    experienceLevel: 'senior',
    geoPosition: [54.36224, 18.646539],
    cityCategory: 'Trójmiasto',
    technologyCategory: 'C++',
    skills: [
      { name: 'JS', level: 3 },
      { name: 'ReactJS', level: 3 },
      { name: 'MongoDB', level: 3 },
      { name: 'NodeJS', level: 3 }
    ],
    body:
      '<div>For our client, an international IT company<strong><em>,</em></strong> we realize a recruitment process on the position (Senior) Backend (Node.js) Developer to the long-term project.</div><div><br></div><div><strong>Information about the project</strong></div><div>We are implementing a self-service and webshop for one of the biggest teleoperators in Finland. We have in total around 30 people working for the project. We are using modern, agile working practices that really appreciates the developers and people have many possibilities to affect the work and how it is done. <br><strong>It is possible to work remotely part-time.</strong></div><div><br></div><div><strong>An ideal candidate profile:</strong></div><ul><li>Very good knowledge of Node.js</li><li>Very good knowledge of JavaScript (there is using Typescript in top of Javascript)</li><li>Good knowledge of REST and/or GraphQL</li><li>Docker knowledge will be a big plus</li></ul><div><br></div><div><strong>Our offer:</strong></div><ul><li>B2B agreement</li><li>Transparent working conditions with both Ework and the Client</li><li>Current support during our cooperation</li><li>Private medical care</li><li>Life insurance</li><li>Multisport</li><li>Teambuilding events</li></ul>'
  },
  {
    id: 'isolution-pl-sql-developer',
    companyName: 'Isolution',
    mainTechnology: 'Data',
    workplace: 'PL/SQL Developer',
    salaryFrom: '10 920',
    salaryTo: '15 960',
    salaryCurrency: 'PLN',
    companySize: '150+',
    employmentType: 'b2b',
    publishedAt: '',
    companyUrl: 'https://isolution.pl/',
    street: 'Tyszkiewicza 21',
    city: 'Warszawa',
    companyLogo:
      'https://bucket.justjoin.it/offers/company_logos/original/8cbc91a494543cdc74e2c5837e5f2326a46e501b.png?1566547398',
    technologies: ['sql', 'git', 'oracle'],
    technologyIcon: 'dataIcon',
    experienceLevel: 'mid',
    geoPosition: [52.239764, 20.967216],
    cityCategory: 'Warszawa',
    technologyCategory: 'Data',
    skills: [
      { name: 'JS', level: 3 },
      { name: 'ReactJS', level: 3 },
      { name: 'MongoDB', level: 3 },
      { name: 'NodeJS', level: 3 }
    ],
    body:
      '<div>For our client, an international IT company<strong><em>,</em></strong> we realize a recruitment process on the position (Senior) Backend (Node.js) Developer to the long-term project.</div><div><br></div><div><strong>Information about the project</strong></div><div>We are implementing a self-service and webshop for one of the biggest teleoperators in Finland. We have in total around 30 people working for the project. We are using modern, agile working practices that really appreciates the developers and people have many possibilities to affect the work and how it is done. <br><strong>It is possible to work remotely part-time.</strong></div><div><br></div><div><strong>An ideal candidate profile:</strong></div><ul><li>Very good knowledge of Node.js</li><li>Very good knowledge of JavaScript (there is using Typescript in top of Javascript)</li><li>Good knowledge of REST and/or GraphQL</li><li>Docker knowledge will be a big plus</li></ul><div><br></div><div><strong>Our offer:</strong></div><ul><li>B2B agreement</li><li>Transparent working conditions with both Ework and the Client</li><li>Current support during our cooperation</li><li>Private medical care</li><li>Life insurance</li><li>Multisport</li><li>Teambuilding events</li></ul>'
  },
  {
    id: 'set-on-target-net-developer',
    companyName: 'Set on Target',
    mainTechnology: '.Net',
    workplace: '.Net Developer',
    salaryFrom: '13 000',
    salaryTo: '18 000',
    salaryCurrency: 'PLN',
    companySize: '30-50',
    employmentType: 'Pernament',
    publishedAt: '',
    companyUrl: 'http://setontarget.com/',
    street: 'Idzikowskiego 16',
    city: 'Warszawa',
    companyLogo:
      'https://bucket.justjoin.it/offers/company_logos/original/4ea733467b425ad3d8e982db962662b4ede6daa4.png?1581413364',
    technologies: ['.net', 'c#', 'wpf'],
    technologyIcon: 'dotNetIcon',
    experienceLevel: 'senior',
    geoPosition: [52.192301, 21.046892],
    cityCategory: 'Warszawa',
    technologyCategory: '.Net',
    skills: [
      { name: 'JS', level: 3 },
      { name: 'ReactJS', level: 3 },
      { name: 'MongoDB', level: 3 },
      { name: 'NodeJS', level: 3 }
    ],
    body:
      '<div>For our client, an international IT company<strong><em>,</em></strong> we realize a recruitment process on the position (Senior) Backend (Node.js) Developer to the long-term project.</div><div><br></div><div><strong>Information about the project</strong></div><div>We are implementing a self-service and webshop for one of the biggest teleoperators in Finland. We have in total around 30 people working for the project. We are using modern, agile working practices that really appreciates the developers and people have many possibilities to affect the work and how it is done. <br><strong>It is possible to work remotely part-time.</strong></div><div><br></div><div><strong>An ideal candidate profile:</strong></div><ul><li>Very good knowledge of Node.js</li><li>Very good knowledge of JavaScript (there is using Typescript in top of Javascript)</li><li>Good knowledge of REST and/or GraphQL</li><li>Docker knowledge will be a big plus</li></ul><div><br></div><div><strong>Our offer:</strong></div><ul><li>B2B agreement</li><li>Transparent working conditions with both Ework and the Client</li><li>Current support during our cooperation</li><li>Private medical care</li><li>Life insurance</li><li>Multisport</li><li>Teambuilding events</li></ul>'
  },
  {
    id: 'mokimo-frontend-developer',
    companyName: 'Makimo',
    mainTechnology: 'JavaScript',
    workplace: 'Frontend Developer',
    salaryFrom: '6 500',
    salaryTo: '10 500',
    salaryCurrency: 'PLN',
    companySize: '20',
    employmentType: 'b2b',
    publishedAt: '',
    companyUrl: 'https://makimo.pl/',
    street: 'Łąkowa 7A',
    city: 'Łódź',
    companyLogo:
      'https://bucket.justjoin.it/offers/company_logos/original/9463733bb39a46ca480a6f6d19fcb2f0dfbcb5f5.jpg?1575286491',
    technologies: ['javascript', 'git', 'react'],
    technologyIcon: 'jsIcon',
    experienceLevel: 'mid',
    geoPosition: [51.761845, 19.438644],
    cityCategory: 'Łódź',
    technologyCategory: 'JS',
    skills: [
      { name: 'JS', level: 3 },
      { name: 'ReactJS', level: 3 },
      { name: 'MongoDB', level: 3 },
      { name: 'NodeJS', level: 3 }
    ],
    body:
      '<div>For our client, an international IT company<strong><em>,</em></strong> we realize a recruitment process on the position (Senior) Backend (Node.js) Developer to the long-term project.</div><div><br></div><div><strong>Information about the project</strong></div><div>We are implementing a self-service and webshop for one of the biggest teleoperators in Finland. We have in total around 30 people working for the project. We are using modern, agile working practices that really appreciates the developers and people have many possibilities to affect the work and how it is done. <br><strong>It is possible to work remotely part-time.</strong></div><div><br></div><div><strong>An ideal candidate profile:</strong></div><ul><li>Very good knowledge of Node.js</li><li>Very good knowledge of JavaScript (there is using Typescript in top of Javascript)</li><li>Good knowledge of REST and/or GraphQL</li><li>Docker knowledge will be a big plus</li></ul><div><br></div><div><strong>Our offer:</strong></div><ul><li>B2B agreement</li><li>Transparent working conditions with both Ework and the Client</li><li>Current support during our cooperation</li><li>Private medical care</li><li>Life insurance</li><li>Multisport</li><li>Teambuilding events</li></ul>'
  },
  {
    id: 'optimo-developer-python-software-developer',
    companyName: 'Optimo Development',
    mainTechnology: 'Python',
    workplace: 'Python Software Developer',
    salaryFrom: '10 000',
    salaryTo: '15 000',
    salaryCurrency: 'PLN',
    companySize: '60+',
    employmentType: 'b2b',
    publishedAt: '',
    companyUrl: 'https://optimodevelopment.com/',
    street: 'Piotrkowska 280 A',
    city: 'Łódź',
    companyLogo:
      'https://bucket.justjoin.it/offers/company_logos/original/98545dfd794ddc4cef49eef6ea99498ecdaccdee.png?1577782424',
    technologies: ['python', 'celery', 'git'],
    technologyIcon: 'pythonIcon',
    experienceLevel: 'senior',
    geoPosition: [51.74581, 19.461549],
    cityCategory: 'Łódź',
    technologyCategory: 'Python',
    skills: [
      { name: 'JS', level: 3 },
      { name: 'ReactJS', level: 3 },
      { name: 'MongoDB', level: 3 },
      { name: 'NodeJS', level: 3 }
    ],
    body:
      '<div>For our client, an international IT company<strong><em>,</em></strong> we realize a recruitment process on the position (Senior) Backend (Node.js) Developer to the long-term project.</div><div><br></div><div><strong>Information about the project</strong></div><div>We are implementing a self-service and webshop for one of the biggest teleoperators in Finland. We have in total around 30 people working for the project. We are using modern, agile working practices that really appreciates the developers and people have many possibilities to affect the work and how it is done. <br><strong>It is possible to work remotely part-time.</strong></div><div><br></div><div><strong>An ideal candidate profile:</strong></div><ul><li>Very good knowledge of Node.js</li><li>Very good knowledge of JavaScript (there is using Typescript in top of Javascript)</li><li>Good knowledge of REST and/or GraphQL</li><li>Docker knowledge will be a big plus</li></ul><div><br></div><div><strong>Our offer:</strong></div><ul><li>B2B agreement</li><li>Transparent working conditions with both Ework and the Client</li><li>Current support during our cooperation</li><li>Private medical care</li><li>Life insurance</li><li>Multisport</li><li>Teambuilding events</li></ul>'
  },
  {
    id: 'appsgardern-frontend-developer',
    companyName: 'appsgarden',
    mainTechnology: 'JavaScript',
    workplace: 'Frontend Developer',
    salaryFrom: '4 000',
    salaryTo: '6 000',
    salaryCurrency: 'PLN',
    companySize: '10',
    employmentType: 'b2b',
    publishedAt: '',
    companyUrl: 'https://www.apps-garden.com/',
    street: 'Makuszyńskiego 4',
    city: 'Kraków',
    companyLogo:
      'https://bucket.justjoin.it/offers/company_logos/original/2834b269600924d94d6065044ad3a1e25ce19caf.png?1544094879',
    technologies: ['react', 'angular', 'git'],
    technologyIcon: 'jsIcon',
    experienceLevel: 'mid',
    geoPosition: [50.08736, 20.048559],
    cityCategory: 'Kraków',
    technologyCategory: 'JS',
    skills: [
      { name: 'JS', level: 3 },
      { name: 'ReactJS', level: 3 },
      { name: 'MongoDB', level: 3 },
      { name: 'NodeJS', level: 3 }
    ],
    body:
      '<div>For our client, an international IT company<strong><em>,</em></strong> we realize a recruitment process on the position (Senior) Backend (Node.js) Developer to the long-term project.</div><div><br></div><div><strong>Information about the project</strong></div><div>We are implementing a self-service and webshop for one of the biggest teleoperators in Finland. We have in total around 30 people working for the project. We are using modern, agile working practices that really appreciates the developers and people have many possibilities to affect the work and how it is done. <br><strong>It is possible to work remotely part-time.</strong></div><div><br></div><div><strong>An ideal candidate profile:</strong></div><ul><li>Very good knowledge of Node.js</li><li>Very good knowledge of JavaScript (there is using Typescript in top of Javascript)</li><li>Good knowledge of REST and/or GraphQL</li><li>Docker knowledge will be a big plus</li></ul><div><br></div><div><strong>Our offer:</strong></div><ul><li>B2B agreement</li><li>Transparent working conditions with both Ework and the Client</li><li>Current support during our cooperation</li><li>Private medical care</li><li>Life insurance</li><li>Multisport</li><li>Teambuilding events</li></ul>'
  }
]
