export const CHANGE_CITY_CATEGORY = 'CHANGE_CITY_CATEGORY'
export const CHANGE_TECHNOLOGY_CATEGORY = 'CHANGE_TECHNOLOGY_CATEGORY'
export const CHANGE_SALARY_RANGE = 'CHANGE_SALARY_RANGE'
export const CHANGE_EXP_LEVEL = 'CHANGE_EXP_LEVEL'
